### ISSUE TITLE
Spanish locale: improve consistency when translating "manage the result as"

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-radon-js#48]
String containing "manage the result as" are currently translated into Spanish with inconsistently:
- "administra el resultado"
- "gestiona el resultado"
- "proporciona el resultado"

We need to agree on one of these formulas and replace all the appearances of the rest.

A fourth option would be "provee el resultado".

**Comment by gabaldon** [comment]
I would say "administra el resultado" or "proporciona el resultado"

**Comment by aesedepece** [comment]
I'm for "proporciona" as well :+1:

**Comment by Tommytrg** [comment]
I prefer "proporciona el resultado"

**Comment by clbartoli** [comment]
"proporciona el resultado" !!

**Comment by Tommytrg** [comment]
Close by https://github.com/witnet/witnet-radon-js/pull/113
