### ISSUE TITLE
Release witnet-radon-js 0.9.2

### ISSUE THREAD

**Issue by gabaldon** [witnet/witnet-radon-js#72]
Update version and deploy

**Comment by aesedepece** [comment]
@gabaldon @Tommytrg are we ok to make the package version bump and release? Or do we need to test integration of this with Sheikah first?

**Comment by Tommytrg** [comment]
I release a new version [two days ago](https://github.com/witnet/witnet-radon-js/commit/5e587afbf47d7b6bc63e6559dae724f977b74ff5), after test it with sheikah
